# Generated by Django 5.1 on 2024-08-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=256)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField()),
                ('emergency_contact', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=32)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('past_medical_history', models.TextField(blank=True, null=True)),
                ('family_medical_history', models.TextField(blank=True, null=True)),
                ('smoking', models.CharField(blank=True, max_length=32, null=True)),
                ('alcohol', models.CharField(blank=True, max_length=32, null=True)),
                ('exercise_frequency', models.CharField(blank=True, max_length=64, null=True)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=256, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=64, null=True)),
                ('insurance_number', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
