# Generated by Django 5.1 on 2024-08-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_patient_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.AddField(
            model_name='patient',
            name='otp_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
