# Generated by Django 5.1 on 2024-08-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_otp_patient_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pid',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
