# Generated by Django 5.1 on 2024-08-28 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_patient_created_at_alter_patient_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('file', models.FileField(upload_to='uploads/')),
                ('analysis_type', models.CharField(max_length=256)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 28, 4, 41, 10, 114866, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
