# Generated by Django 5.1 on 2024-08-28 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_healthreport_analysis_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=32)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('exercise', models.CharField(max_length=32)),
                ('diet', models.CharField(max_length=256)),
                ('medicalConditions', models.TextField()),
                ('stress', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 28, 8, 40, 14, 85244, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
