# Generated by Django 5.1 on 2024-08-28 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contact_personalassistant_alter_patient_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 28, 8, 42, 17, 886931, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
