# Generated by Django 5.1 on 2024-08-29 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_chatbot_alter_patient_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalassistant',
            name='occupation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 29, 18, 27, 33, 280778, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
