# Generated by Django 5.1 on 2024-08-29 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_personalassistant_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalassistant',
            name='reccomendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 29, 18, 45, 23, 402687, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
