# Generated by Django 5.1 on 2024-08-31 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_patient_created_at_analyzedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedreport',
            name='gemini_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 31, 9, 15, 33, 385508, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
