# Generated by Django 5.1 on 2024-09-02 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_analyzedreport_gemini_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 2, 10, 32, 7, 71547, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
